---
- hosts: testvm
  become: yes

  tasks:

  - name: add source repository
    apt_repository:
      repo: deb-src http://httpredir.debian.org/debian sid main
      state: present

  - name: add en_US locale
    lineinfile:
      path: /etc/locale.gen
      line: 'en_US.UTF-8 UTF-8'

  - name: regenerate locales
    command: locale-gen

  - name: install build tools
    apt:
      update_cache: yes
      state: latest
      name: "{{ item }}"
    with_items:
      - build-essential
      - fakeroot
      - devscripts

  - name: install package build-dependencies
    shell: yes | mk-build-deps -ir "{{ package }}"

  - name: check if package folder exists
    stat:
      path: "{{ package }}"
    register: pkg_folder

  - name: debcheckout package
    command: debcheckout "{{ package }}"
    when: not pkg_folder.stat.exists

  - name: build package
    command: dpkg-buildpackage -uc -us -b
    args:
      chdir: "{{ package }}"

  - name: remove package build dependencies
    apt:
      state: absent
      name: "{{ package }}-build-deps"
      autoremove: yes

  - name: list deb files
    shell: find . -name "*.deb"
    register: deb_result

  - name: install debs
    apt:
      deb: "{{ item }}"
    with_items: "{{ deb_result.stdout_lines }}"

  - name: find package reverse build dpendencies
    shell: grep Package "{{ package }}/debian/control" | cut -d: -f2 | xargs build-rdeps --only-main --old --quiet
    register: rdeps_result
