---
- hosts: testvm

  tasks:

  - name: add source repository
    apt_repository:
      repo: deb-src http://httpredir.debian.org/debian sid main
      state: present
    become: yes

  - name: add en_US locale
    lineinfile:
      dest: /etc/locale.gen
      line: 'en_US.UTF-8 UTF-8'
    register: locale_added
    become: yes

  - name: re-generate locales
    command: locale-gen
    when: locale_added.changed
    become: yes

  - name: install {{ package }} build-dependencies
    shell: yes | mk-build-deps -ir "{{ package }}"
    become: yes

  - name: check if {{ package }} folder exists
    stat:
      path: "{{ package }}"
    register: pkg_folder

  - name: debcheckout {{ package }}
    command: debcheckout "{{ package }}"
    when: not pkg_folder.stat.exists

  - name: build {{ package }}
    command: dpkg-buildpackage -uc -us -b
    args:
      chdir: "{{ package }}"

  - name: remove {{ package }} build dependencies
    apt:
      state: absent
      name: "{{ package }}-build-deps"
      autoremove: yes
    become: yes

  - name: list deb files
    shell: find . -name "*{{ package }}*.deb"
    register: deb_result

  - name: install debs
    apt:
      deb: "{{ item }}"
    with_items: "{{ deb_result.stdout_lines }}"
    become: yes

  - name: find {{ package }} reverse build dpendencies
    shell: >
      grep Package "{{ package }}/debian/control"
      | cut -d: -f2
      | xargs build-rdeps --only-main --old --quiet
    register: build_rdeps_result

  - name: rebuild {{ package }} reverse build dpendencies
    include: rebuild.yml pkg={{item}}
    static: no
    with_items: "{{ build_rdeps_result.stdout_lines }}"
