---
- hosts: testvm
  become: yes

  tasks:

  - name: add source repository
    apt_repository:
      repo: deb-src http://httpredir.debian.org/debian sid main
      state: present

  - name: add en_US locale
    lineinfile:
      dest: /etc/locale.gen
      line: 'en_US.UTF-8 UTF-8'
    register: locale_added

  - name: regenerate locales
    command: locale-gen
    when: locale_added.changed

  - name: install build tools
    apt:
      update_cache: yes
      state: latest
      name: "{{ item }}"
    with_items:
      - build-essential
      - fakeroot
      - devscripts

  - name: rebuild the package
    include: rebuild.yml pkg={{package}}

  - name: list deb files
    shell: find . -name "*.deb"
    register: deb_result

  - name: install debs
    apt:
      deb: "{{ item }}"
    with_items: "{{ deb_result.stdout_lines }}"

  - name: find package reverse build dpendencies
    shell: >
      grep Package "{{ package }}/debian/control"
      | cut -d: -f2
      | xargs build-rdeps --only-main --old --quiet
    register: build_rdeps_result

  - name: rebuild package reverse build dpendencies
    include: rebuild.yml pkg={{item}}
    static: no
    with_items: "{{ build_rdeps_result.stdout_lines }}"
