---
- hosts: localhost
  become: yes

  vars:
    image_file: image.img

  tasks:
  - name: check if image exists
    stat:
      path: "{{ image_file }}"
    register: image

  - name: vmdebootstrap image
    command: >
      vmdebootstrap
        --arch {{ arch }}
        --distribution sid
        --image {{ image_file }}
        --size 10G
        --hostname {{ hostvars['vm'].ansible_user }}
        --user {{ hostvars['vm'].ansible_user }}/{{ ansible_ssh_pass }}
        --sudo
        --grub
        --configure-apt
        --serial-console
        --package openssh-server
        --package python
        --package locales
        --package build-essential
        --package fakeroot
        --package devscripts
        --package subversion
        --package git
        --package equivs
        --package dctrl-tools
        --package ca-certificates
        --package dose-extra
    when: not image.stat.exists

  - name: fire up vm
    command: >
      kvm
        -name {{ hostvars['vm'].ansible_user }}
        -smp 4
        -m 4096
        -display none
        -drive file={{ image_file }}
        -net nic
        -net user,hostfwd=tcp:{{ hostvars['vm'].ansible_host }}:{{ hostvars['vm'].ansible_port }}-:22
    async: 10000
    poll: 0

  - name: wait for testvm to come up
    wait_for:
      host: "{{ hostvars['vm'].ansible_host }}"
      port: "{{ hostvars['vm'].ansible_port }}"
      delay: 20

